#!/bin/bash

shopt -s extglob

# 1. Write a script called mycase, using the case utility
#  to checks the type of character entered by a user:
# a. Upper Case.
# b. Lower Case.
# c. Number.
# d. Nothing.

read -p "Enter an input : " inp

case $inp in
[A-Z])
  echo upperCase
  ;;
[a-z])
  echo lowerCase
  ;;
[0-9])
  echo number
  ;;
*)
  echo nothing
  ;;
esac
