#!/bin/bash

#   3. Write a script called mychmod using
# for utility to give execute permission
# to all files and
# directories in your home directory.

my_dir=/home/abougabal/ahmed_commands/Day3/question3_assets
for file in "$my_dir"/*; do

  if [ -f "$file" ]; then
    chmod u+x $file
    echo "changed permission for $file"
  fi

done
